comment: false
github_checks:
  annotations: true
coverage:
  precision: 1
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
