# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }}, ${{ matrix.config.qgis }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest, qgis: 'none', r: 'release'}
          - {os: macOS-latest, qgis: 'macos-brew', r: 'release'}
          - {os: windows-latest, qgis: 'windows-chocolatey', r: 'release'}
          - {os: ubuntu-22.04, qgis: 'ubuntu-nightly', r: 'release'}
          - {os: ubuntu-22.04, qgis: 'ubuntu', r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install QGIS (Ubuntu Nightly)
        if: matrix.config.qgis == 'ubuntu-nightly'
        run: |
          sudo wget -qO /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg
          sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/qgis-archive-keyring.gpg] https://qgis.org/ubuntu `lsb_release -c -s` main" > /etc/apt/sources.list.d/qgis.list'
          sudo apt-get update
          sudo apt-get install -y qgis qgis-plugin-grass saga

      - name: Install QGIS (Ubuntu)
        if: matrix.config.qgis == 'ubuntu'
        run: |
          sudo wget -qO /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg
          sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/qgis-archive-keyring.gpg] https://qgis.org/ubuntu `lsb_release -c -s` main" > /etc/apt/sources.list.d/qgis.list'
          sudo apt-get update
          sudo apt-get install -y qgis qgis-plugin-grass saga

      - name: Install QGIS (MacOS homebrew)
        if: matrix.config.qgis == 'macos-brew'
        run: |
          brew install --cask qgis

# installs last nightly build of QGIS
# works locally, hangs on GHA after download
# leaving this out until can figure out how to run reliably
      - name: Install QGIS (MacOS nightly)
        if: matrix.config.qgis == 'macos-nightly'
        run: |
          curl https://qgis.org/downloads/macos/qgis-macos-nightly.dmg --output qgis-macos-nightly.dmg
          yes | hdiutil attach -nobrowse -noverify -mountpoint qgis qgis-macos-nightly.dmg > /dev/null
          sudo cp -R qgis/QGIS.app /Applications

      - name: Install QGIS (Windows chocolatey)
        if: matrix.config.qgis == 'windows-chocolatey'
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install qgis

      - uses: r-lib/actions/check-r-package@v2

      # run with CMD check because installing QGIS is expensive
      - name: Test Coverage
        if: matrix.config.qgis == 'macos-brew'
        run: |
          install.packages("covr")
          covr::codecov()
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Show platform-info output
        if: always()
        run: find check -name 'platform-info.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-${{ matrix.config.qgis }}-results
          path: check
